[firebase]
type = "service_account"
project_id = "tbchestapp"
private_key_id = "e215487f75a16e5c7306b207b374aeb8d234359a"
private_key = """
-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCvVTwh+ffhskf3
tSCPaCVAqxib7zABRNjkE/hU7IlyJJARq2GVdD/iBQQeFXcpmpaaFy8mf3iHy4ZK
NGXlt5LfzANTeVUyQ8KGvvnNrk5K0eMYm+BBXL5DtKOHSTulE1fGIDOYYKTBRiDb
Eb3jLT2ghr+zVpDVIqOxcN/tICd5e9xj+XPKXXLl20ZC/hzhEHCddLYRJlu1E5pK
gBYLFZndo+buytHVHy+PdIWBksS2GxG+hCbvj9jkoRcrL8lnoazCgaR29cj/b+Lf
W5iuWd9Dq9NHx3pQ3gFU+TW5sR7OBJHv1kaW+qMvYacjqEZCRsT7HGzMhk+g0RRX
JWZNfq87AgMBAAECggEAHtKMFKj946ZUsn4b8DntupWZaOg+dyqkOkwsbrl6XB+D
WCfZqs1Z4aDiHWvGnAC6EvKablkgVjb4L5lQhHamEkOqHgWJbaGt08RE49yNlOea
1Zupa7QjGoHp8YF1Q8rHtmO4zkPHEtcCNaDD0ekFGXA2yQ8hvOYvAqWGKAhsCBXs
IjrNdNKcuxVxtOzJbWSmXzi/OGv/WXStIrk0bb7BwLfOnmEgwiejRknUTzHeBCm8
WoMAWmTtaKt1JLPe7x8ffpdq5IMpulBv6TehxTEYRYwXdHl+NKZ0/mjsU4OuKxth
IvYVGDV5G+2uPS5O63nB9sUIaXZdCtQz1PPdlaGZeQKBgQDuT2ZF0UcbhqLm8y2C
mA45lPr+N1ZOdRbNsKV15hZiVUfnAlaVb1/U9tYrYdHghLorlwpsQrXiO+GqE/Le
X/DXGSuqtsVJeJuo4JwECMIFqb4rm9ud6e6QHNu5OEwPriHsnX7waBH7PJNwxmRt
dIIX58ztQny2F1WRaDmH7hwuRQKBgQC8WRTdO5dRW2T5HMk9bC6BVzMGjSXZccKo
ZS8xT5EgZAn6JGkOWci+WD56/MCqG73QFX3Ma6Dtqz1JOUHFKrVrp6B4L45rAbnN
NlTbWxG9gCUM0/alF7SLTwxh8UYXTmy3n6QEhGZfFEYhriguLc/BFY4LVpo+HlSt
jGGOvwn/fwKBgQCaSl/d7hwKr0XDH0ik18vF7jX+51cCnv5vl+HYjmqJqctOvo3O
XHiASnvpRID8yxI57KV76EkYO0rksdu5rAYjTZGfCox7ABJP6XQ5jG4J+pc8ZsFu
4SlqtrRvnApq0IP4TRQFlGun7NVM27Xjw94CmjpslnJl9n+ZEBDHeBtYvQKBgE/U
LdyqwjLQWtae1ch7zqYxUEYpku47ojZ/VGZBBBDHddcYkZJsiYHroue7sukmgufs
A/qdb4LsfjhH1VF9DZHIZWIrPeCqxZZtvb+PNNCtvIZYXISSrIoTAfuNKJj+O2QE
fJ8RgtYvoJ3r08nmztRWj3LMzOkhL+CyzDKVU+Z/AoGAN6+B5G407zZh3yerLxcU
M/JcgMPsjA3IMnb1LhNAnPyGBC+VT1nCFNbUG1IRCOomoNkEt/84RpNMxxIFQkaK
Dcm99URIbhzBpHp9vlkkRS4592CV9ZgyK+kMpnz+A9sP1oUHOmvWhNPCjfTOYKUs
0bvdZ7LycGcpPrO8suWZLnI=
-----END PRIVATE KEY-----
"""
client_email = "firebase-adminsdk-fbsvc@tbchestapp.iam.gserviceaccount.com"
client_id = "100144488426604586122"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40tbchestapp.iam.gserviceaccount.com"
universe_domain = "googleapis.com"